# Generated by Django 3.2.8 on 2021-11-23 16:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=1024, unique=True)),
                ('content', models.TextField()),
                ('image', models.URLField()),
                ('is_draft', models.BooleanField(default=False)),
                ('order', models.PositiveSmallIntegerField(unique=True)),
                ('link', models.URLField()),
                ('is_approved', models.BooleanField(default=False)),
                ('start_time', models.DateTimeField()),
                ('expire_time', models.DateTimeField(null=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
