# Generated by Django 4.0.1 on 2022-01-25 20:00

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioBook',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.product')),
                ('intro', models.URLField()),
                ('published_year', models.PositiveSmallIntegerField()),
                ('is_downloadable', models.BooleanField(default=False)),
                ('audio_publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_publisher', to='base.publisher')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('base.product',),
        ),
        migrations.CreateModel(
            name='AudioIndex',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=1024)),
                ('file', models.URLField()),
                ('duration', models.PositiveIntegerField()),
                ('is_downloadable', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AudioType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=3, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompatibleDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=3, unique=True)),
                ('version', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PaperBook',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.product')),
                ('intro', models.URLField()),
                ('published_year', models.PositiveSmallIntegerField()),
                ('authors', models.ManyToManyField(to='base.Author')),
                ('book_publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paper_book_publisher', to='base.publisher')),
                ('translators', models.ManyToManyField(to='base.Translator')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('base.product',),
        ),
        migrations.CreateModel(
            name='PaperBookComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('message', models.CharField(max_length=500)),
                ('is_approved', models.BooleanField(default=False)),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paper_book_comments', to='product.paperbook')),
                ('reply_to', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='product.paperbookcomment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paper_book_comment_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AudioBookComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('message', models.CharField(max_length=500)),
                ('is_approved', models.BooleanField(default=False)),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_book_comments', to='product.audiobook')),
                ('reply_to', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='product.audiobookcomment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_book_comment_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='audiobook',
            name='audio_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='product.audiotype'),
        ),
        migrations.AddField(
            model_name='audiobook',
            name='authors',
            field=models.ManyToManyField(to='base.Author'),
        ),
        migrations.AddField(
            model_name='audiobook',
            name='book_publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_book_publisher', to='base.publisher'),
        ),
        migrations.AddField(
            model_name='audiobook',
            name='compatible_devices',
            field=models.ManyToManyField(to='product.CompatibleDevice'),
        ),
        migrations.AddField(
            model_name='audiobook',
            name='indices',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='product.audioindex'),
        ),
        migrations.AddField(
            model_name='audiobook',
            name='speakers',
            field=models.ManyToManyField(to='base.Speaker'),
        ),
        migrations.AddField(
            model_name='audiobook',
            name='translators',
            field=models.ManyToManyField(to='base.Translator'),
        ),
        migrations.CreateModel(
            name='PaperBookStar',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('star', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paper_book_stars', to='product.paperbook')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paper_book_star_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
                'unique_together': {('user', 'product')},
            },
        ),
        migrations.CreateModel(
            name='AudioBookStar',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('star', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_book_stars', to='product.audiobook')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_book_star_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
                'unique_together': {('user', 'product')},
            },
        ),
    ]
